project:
  type: website
  output-dir: docs

website:
  title: "Learning Web Security - Themes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: server-side-web-security.qmd
        text: Server-Side Web Security
      - href: client-side-web-security.qmd
        text: Client-Side Web Security     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
